repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: local
    hooks:
    -   id: black
        language_version: python3.6
        name: black
        entry: black
        language: system
        types: [python]
-   repo: local
    hooks:
    -   id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
-   repo: local
    hooks:
    -   id: bandit
        name: bandit
        entry: bandit -n 3 -lll
        language: system
        types: [python]
